<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>sinpe_validator_api.Domain</RootNamespace>
    <AssemblyName>sinpe_validator_api.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Constants\" />
    <Folder Include="Entities\" />
    <Folder Include="Enums\" />
    <Folder Include="Events\" />
    <Folder Include="Exceptions\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

</Project>
